# Generated by Django 3.1 on 2021-11-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211116_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
