# Generated by Django 3.1 on 2021-11-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211116_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
